### ISSUE TITLE
ENH: change default positions for `CrossSectionMainWindow`

### ISSUE THREAD

**Issue by CJ-Wright** [Nikea/xray-vision#78]
Would it be possible set the default color map, scale and other features as kwargs in the `CrossSectionMainWindow` initial setup?

**Comment by ericdill** [comment]
Almost certainly.  Want to submit a PR with the changes you want to see?

**Comment by CJ-Wright** [comment]
Sure, it might take me a while

**Comment by CJ-Wright** [comment]
See #79

**Comment by ericdill** [comment]
Closed in #79
